---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.10
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Install dependencies
          command: pipenv install --dev
      - run:
          name: Run pytest
          command: pipenv run pytest --junitxml=test-results/pytest/results.xml
      - store_test_results:
          path: test-results
