---
name: Continuous Integration

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install poetry
          poetry install
      - name: Lint
        run: poetry run black --check .
      - name: Test
        run: poetry run pytest
